### ISSUE TITLE
I have an error about the key 'swin_t'.

### ISSUE THREAD

**Issue by Mr-corton** [moon-wh/MADE#5]
Traceback (most recent call last):
  File "D:\MADE-master\SOLIDER\demo_PETA_prcc.py", line 136, in <module>
    main(cfg, args)
  File "D:\MADE-master\SOLIDER\demo_PETA_prcc.py", line 46, in main
    backbone, c_output = build_backbone(cfg.BACKBONE.TYPE, cfg.BACKBONE.MULTISCALE)
  File "D:\MADE-master\SOLIDER\models\model_factory.py", line 15, in build_backbone
    model = BACKBONE[key]()
KeyError: 'swin_t'

进程已结束,退出代码1

**Comment by moon-wh** [comment]
Maybe you can find a solution to your problem within the project [SOLIDER](https://github.com/tinyvision/SOLIDER-PersonAttributeRecognition).

**Comment by Serinmq** [comment]
Have you solved the problem yet?
